version: '3'

services:
  app:
    image: spaceonfire/nginx-php-fpm:latest-7.2
    environment:
#      - SOF_PRESET=default
      - SOF_PRESET=bitrix
      - APPLICATION_ENV=test
      - ENABLE_XDEBUG=1
      - XDEBUG_IDEKEY=dompdf
      - PAGER=more
      - PUID=1000
    volumes:
      - ./:/var/www/html
    ports:
      - 8888:8080
